# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Raúl Andrés Casanova Sosa - CV
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Curriculum Vitae - Raúl Andrés Casanova Sosa
baseurl: "/bio" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
twitter_username: erreaceese
gitlab_username:  alcaravanosu
telegram_username: alcaravan_osu

# Build settings
markdown: kramdown
exclude: ["README.md"]
